name = "RISTD Scratch"
author = "AlistairKion&ajsnarr98"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49b916b0c8a5c0350eca8eab40490e3d835fe4220b2903a846094ce76aacafc8"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
