name = "RISTD Scratch"
author = "AlistairKion&ajsnarr98"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de0a93d78071dc925b7da6552f5286a0b7cc9a34aff8604658ac5f08b4466042"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
