name = "RISTD Scratch"
author = "AlistairKion&ajsnarr98"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eb33ecd668ce0b948b2b8ba0bc21bad579e0e4658aa8c10195f515233702186"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
